C:\VulkanSDK\1.4.321.1\Bin\glslc.exe voxel_cone_tracing/conservative_radiance_voxelization.vert -o voxel_cone_tracing/cons_voxelization.vert.spv 
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe voxel_cone_tracing/conservative_radiance_voxelization.geom -o voxel_cone_tracing/cons_voxelization.geom.spv 
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe voxel_cone_tracing/conservative_radiance_voxelization.frag -o voxel_cone_tracing/cons_voxelization.frag.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe voxel_cone_tracing/visualization/texture3DVisualization.vert -o voxel_cone_tracing/visualization/texture3DVisualization.vert.spv 
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe voxel_cone_tracing/visualization/texture3DVisualization.geom -o voxel_cone_tracing/visualization/texture3DVisualization.geom.spv 
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe voxel_cone_tracing/visualization/texture3DVisualization.frag -o voxel_cone_tracing/visualization/texture3DVisualization.frag.spv 
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe voxel_cone_tracing/unpack_and_filter.comp -o voxel_cone_tracing/unpack_and_filter.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe skybox.vert -o skybox.vert.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe skybox.frag -o skybox.frag.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe cascaded_shadows.vert -o cascaded_shadows.vert.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe cascaded_shadows.frag -o cascaded_shadows.frag.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe cascaded_shadows.geom -o cascaded_shadows.geom.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe hdr.vert -o hdr.vert.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe hdr.frag -o hdr.frag.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe depth_pass.vert -o depth_pass.vert.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe filter_cube.vert -o filter_cube.vert.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe irradiance_cube.frag -o irradiance_cube.frag.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe irradiance_cube.comp -o irradiance_cube.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe brdf_lut.comp -o brdf_lut.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe pre_filter.comp -o pre_filter.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe pre_filter_envmap.frag -o pre_filter_envmap.frag.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe gen_brdf_lut.vert -o gen_brdf_lut.vert.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe gen_brdf_lut.frag -o gen_brdf_lut.frag.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe pre_filter_envmap.frag -o pre_filter_envmap.frag.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe cluster_shader.comp -o cluster_shader.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe cluster_cull_light_shader.comp -o cluster_cull_light_shader.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe indirect_cull.comp -o indirect_cull.comp.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe depth_reduce.comp -o depth_reduce.comp.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe indirect_forward.vert -o indirect_forward.vert.spv
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe indirect_forward.frag -o indirect_forward.frag.spv 
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe upsample.comp -o upsample.spv 
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe downsample.comp -o downsample.spv 
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe upsample.frag -o upsample.frag.spv 
C:\VulkanSDK\1.4.321.1\Bin\glslc.exe pbr_test.frag -o pbr_test.frag.spv 
pause